name: Mapping Example

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  demo_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Get all python dependencies for RePort
        run: |
          python3 -m venv myenv
          source myenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup RePort
        run: |
          cd src
          sudo -E python -p RePort.report -install

      - name: Run Graybox Mapping on the demo firmware
        run: |
          cd src
          python3 -m RePort.report -gray -firmware ../DIR-868L_fw_revB_2-05b02_eu_multi_20161117.zip
                
      - name: Package the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports-artifact
          path: reports/