name: Mapping Example

on:
  workflow_dispatch:


jobs:
  demo_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies and RePort
        run: |
          sudo apt-get update
          sudo apt-get install -y liblzo2-dev

          python -m venv myenv
          source myenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

          cd src
          sudo -E ../myenv/bin/python -m RePort.report -install

     
      - name: Run Graybox Mapping on the demo firmware
        run: |
          source myenv/bin/activate
          cd src
          sudo -E ../myenv/bin/python -m RePort.report -gray -firmware ../DIR-868L_fw_revB_2-05b02_eu_multi_20161117.zip
      
      - name: Package the artifacts
        run: |
          zip -r reports.zip reports/ || true
      
      - name: Package the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports-artifact
          path: reports.zip