name: Scan Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  demo_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Binwalk from the open source repo (Paizei na to allajw)
      - name: Install binwalk
        run: |
          sudo apt install curl
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          . $HOME/.cargo/env
          sudo apt install git
          git clone https://github.com/ReFirmLabs/binwalk
          sudo ./binwalk/dependencies/ubuntu.sh
          cd binwalk
          cargo build --release
          sudo ln -s $PWD/target/release/binwalk /usr/local/bin/binwalk

      - name: Ensure all needed tools are installed
        run: |
          sudo apt-get update
          sudo apt-get install -y coreutils
          sudo apt-get install 7zip-standalone
          sudo apt-get install binutils
          sudo apt-get install binutils-arm-linux-gnueabi

      - name: Install angr
        run: |
          # Install angr and dependencies using pip
          python3 -m pip install --upgrade pip
          python3 -m pip install angr
      
      - name: Download firmware from Google Drive
        run: |
          wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1N7G8-tUa3lRRTqmrepPpcY02p3fM0aTj' -O firmware.bin

      - name: Run the Analysis
        run: |
          python3 ./demo.py firmware.bin

      # - name: Upload extracted firmware
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: extracted-firmware
      #     path: temp_firmware.bin